# Generated by Django 3.2.3 on 2021-05-24 23:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('coord_start', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('coord_end', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('length', models.DecimalField(decimal_places=7, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='RoadSpeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('speed', models.FloatField()),
                ('intensity', models.IntegerField()),
                ('caracterization', models.CharField(max_length=8)),
                ('road_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic_monitoring.road')),
            ],
        ),
        migrations.AddConstraint(
            model_name='roadspeed',
            constraint=models.UniqueConstraint(fields=('time', 'road_id'), name='unique-reading'),
        ),
    ]
