# Generated by Django 3.2.3 on 2021-05-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='length',
            field=models.DecimalField(decimal_places=7, max_digits=15),
        ),
    ]
